name: Mirror to gitee Repo

on: [ push, delete, create ]

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:kdcloudone/kdesign-pro.git'
          destination-repo: 'https://gitee.com/kdcloudone/kdesign-pro.git'